#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
set -e

bunx lint-staged

echo "Running Type Checks..."

# Frontend
echo "Frontend (TSC)..."
(cd app && bunx tsc -b)

# Backend
echo "Backend (Mypy)..."
(cd api && uv run mypy .)
